Name(7)
=======


NAME
----
fty-rest - Overview of Common core REST API for 42ity project


SYNOPSIS
--------

Project fty-rest aims to ... (short marketing pitch)

It delivers several programs with their respective man pages:

and public classes in a shared library:
 db/topology2.3 git_details_override.3 shared/augtool.3 shared/cidr.3 shared/configure_inform.3 shared/csv.3 shared/data.3 shared/dbpath.3 shared/filesystem.3 shared/ic.3 shared/log.3 shared/data.3 shared/str_defs.3 shared/tntmlm.3 shared/topic_cache.3 shared/upsstatus.3 shared/utils.3 shared/utils++.3 shared/utils_web.3 web/src/asset_computed_impl.3 web/src/helpers.3 web/src/iface.3 web/src/location_helpers.3 web/src/sasl.3 web/src/tokens.3

Generally you can compile and link against it like this:
----
#include <fty-rest.h>

cc ['flags'] 'files' -lfty_rest ['libraries']
----


DESCRIPTION
-----------

This is a skeleton document created by zproject, which will not be
regenerated automatically (by Makefiles nor project.xml re-parsing).
You should add hand-written text here to detail whatever applies to
Linux standard manpage Section 7 (note that other OSes may follow
a different standard with similar concepts, and extend the recipes
to package this document into a different section number):

----
7 Overview, conventions, and miscellaneous :
    Overviews or descriptions of various topics, conventions
    and protocols, character set standards, the standard
    filesystem layout, and miscellaneous other things.
----

Classes
~~~~~~~

Something for developers to consider. Note there are separate man
pages generated for public classes during build with contents taken
from source code comments.
