// WARNING: This file is generated during make, DO NOT EDIT
#ifndef BIOS_GIT_DETAILS_OVERRIDE
#define BIOS_GIT_DETAILS_OVERRIDE
#ifdef HAVE_PACKAGE_GIT
#undef HAVE_PACKAGE_GIT
#endif
#define HAVE_PACKAGE_GIT 1
#ifdef HAVE_PACKAGE_BUILD_HOST
#undef HAVE_PACKAGE_BUILD_HOST
#endif
#define HAVE_PACKAGE_BUILD_HOST 1
#ifdef HAVE_PACKAGE_BUILD_TSTAMP
#undef HAVE_PACKAGE_BUILD_TSTAMP
#endif
#define HAVE_PACKAGE_BUILD_TSTAMP 1
#ifdef PACKAGE_BUILD_HOST_UNAME_ESCAPED
#undef PACKAGE_BUILD_HOST_UNAME_ESCAPED
#endif
extern char * PACKAGE_BUILD_HOST_UNAME_ESCAPED;
#ifdef PACKAGE_BUILD_HOST_NAME_ESCAPED
#undef PACKAGE_BUILD_HOST_NAME_ESCAPED
#endif
extern char * PACKAGE_BUILD_HOST_NAME_ESCAPED;
#ifdef PACKAGE_BUILD_HOST_OS_ESCAPED
#undef PACKAGE_BUILD_HOST_OS_ESCAPED
#endif
extern char * PACKAGE_BUILD_HOST_OS_ESCAPED;
#ifdef PACKAGE_BUILD_TSTAMP_ESCAPED
#undef PACKAGE_BUILD_TSTAMP_ESCAPED
#endif
extern char * PACKAGE_BUILD_TSTAMP_ESCAPED;
#ifdef PACKAGE_BUILD_TSTAMP_ISO8601_ESCAPED
#undef PACKAGE_BUILD_TSTAMP_ISO8601_ESCAPED
#endif
extern char * PACKAGE_BUILD_TSTAMP_ISO8601_ESCAPED;
#ifdef PACKAGE_GIT_ORIGIN_ESCAPED
#undef PACKAGE_GIT_ORIGIN_ESCAPED
#endif
extern char * PACKAGE_GIT_ORIGIN_ESCAPED;
#ifdef PACKAGE_GIT_BRANCH_ESCAPED
#undef PACKAGE_GIT_BRANCH_ESCAPED
#endif
extern char * PACKAGE_GIT_BRANCH_ESCAPED;
#ifdef PACKAGE_GIT_TSTAMP_ESCAPED
#undef PACKAGE_GIT_TSTAMP_ESCAPED
#endif
extern char * PACKAGE_GIT_TSTAMP_ESCAPED;
#ifdef PACKAGE_GIT_HASH_S_ESCAPED
#undef PACKAGE_GIT_HASH_S_ESCAPED
#endif
extern char * PACKAGE_GIT_HASH_S_ESCAPED;
#ifdef PACKAGE_GIT_HASH_L_ESCAPED
#undef PACKAGE_GIT_HASH_L_ESCAPED
#endif
extern char * PACKAGE_GIT_HASH_L_ESCAPED;
#ifdef PACKAGE_GIT_STATUS_ESCAPED
#undef PACKAGE_GIT_STATUS_ESCAPED
#endif
extern char * PACKAGE_GIT_STATUS_ESCAPED;
#ifdef PACKAGE_GIT_TAGGED_ESCAPED
#undef PACKAGE_GIT_TAGGED_ESCAPED
#endif
extern char * PACKAGE_GIT_TAGGED_ESCAPED;
#ifdef PACKAGE_GIT_TSTAMP_ISO8601_ESCAPED
#undef PACKAGE_GIT_TSTAMP_ISO8601_ESCAPED
#endif
extern char * PACKAGE_GIT_TSTAMP_ISO8601_ESCAPED;
#endif // BIOS_GIT_DETAILS_OVERRIDE
