/*  =========================================================================
    fty_rest_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_REST_CLASSES_H_INCLUDED
#define FTY_REST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty_rest.h"

//  Extra headers
#include "db/agentstate.h"
#include "db/assetdef.h"
#include "db/assets.h"
#include "db/dbhelpers.h"
#include "db/inout.h"
#include "db/types.h"

//  Opaque class structures to allow forward references
#ifndef DB/AGENTSTATE/AGENTSTATE_T_DEFINED
typedef struct _db/agentstate/agentstate_t db/agentstate/agentstate_t;
#define DB/AGENTSTATE/AGENTSTATE_T_DEFINED
#endif
#ifndef DB/ASSET_GENERAL_T_DEFINED
typedef struct _db/asset_general_t db/asset_general_t;
#define DB/ASSET_GENERAL_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETCR_T_DEFINED
typedef struct _db/assets/assetcr_t db/assets/assetcr_t;
#define DB/ASSETS/ASSETCR_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETD_T_DEFINED
typedef struct _db/assets/assetd_t db/assets/assetd_t;
#define DB/ASSETS/ASSETD_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETR_T_DEFINED
typedef struct _db/assets/assetr_t db/assets/assetr_t;
#define DB/ASSETS/ASSETR_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETU_T_DEFINED
typedef struct _db/assets/assetu_t db/assets/assetu_t;
#define DB/ASSETS/ASSETU_T_DEFINED
#endif
#ifndef DB/INOUT/EXPORTCSV_T_DEFINED
typedef struct _db/inout/exportcsv_t db/inout/exportcsv_t;
#define DB/INOUT/EXPORTCSV_T_DEFINED
#endif
#ifndef DB/INOUT/IMPORTCSV_T_DEFINED
typedef struct _db/inout/importcsv_t db/inout/importcsv_t;
#define DB/INOUT/IMPORTCSV_T_DEFINED
#endif
#ifndef MSG/ASSET_MSG_T_DEFINED
typedef struct _msg/asset_msg_t msg/asset_msg_t;
#define MSG/ASSET_MSG_T_DEFINED
#endif
#ifndef MSG/COMMON_MSG_T_DEFINED
typedef struct _msg/common_msg_t msg/common_msg_t;
#define MSG/COMMON_MSG_T_DEFINED
#endif
#ifndef PERSIST/ASSETCRUD_T_DEFINED
typedef struct _persist/assetcrud_t persist/assetcrud_t;
#define PERSIST/ASSETCRUD_T_DEFINED
#endif
#ifndef PERSIST/ASSETTOPOLOGY_T_DEFINED
typedef struct _persist/assettopology_t persist/assettopology_t;
#define PERSIST/ASSETTOPOLOGY_T_DEFINED
#endif
#ifndef PERSIST/DBHELPERS_T_DEFINED
typedef struct _persist/dbhelpers_t persist/dbhelpers_t;
#define PERSIST/DBHELPERS_T_DEFINED
#endif
#ifndef PERSIST/MONITOR_T_DEFINED
typedef struct _persist/monitor_t persist/monitor_t;
#define PERSIST/MONITOR_T_DEFINED
#endif
#ifndef PERSIST/PERSIST_ERROR_T_DEFINED
typedef struct _persist/persist_error_t persist/persist_error_t;
#define PERSIST/PERSIST_ERROR_T_DEFINED
#endif
#ifndef SHARED/MAGIC_T_DEFINED
typedef struct _shared/magic_t shared/magic_t;
#define SHARED/MAGIC_T_DEFINED
#endif
#ifndef WARRANTY/WARRANTY-METRIC_T_DEFINED
typedef struct _warranty/warranty-metric_t warranty/warranty-metric_t;
#define WARRANTY/WARRANTY-METRIC_T_DEFINED
#endif
#ifndef WEB/SRC/ADD_GPIO_T_DEFINED
typedef struct _web/src/add_gpio_t web/src/add_gpio_t;
#define WEB/SRC/ADD_GPIO_T_DEFINED
#endif
#ifndef WEB/SRC/ADMIN_IFACE_T_DEFINED
typedef struct _web/src/admin_iface_t web/src/admin_iface_t;
#define WEB/SRC/ADMIN_IFACE_T_DEFINED
#endif
#ifndef WEB/SRC/ADMIN_IFACES_T_DEFINED
typedef struct _web/src/admin_ifaces_t web/src/admin_ifaces_t;
#define WEB/SRC/ADMIN_IFACES_T_DEFINED
#endif
#ifndef WEB/SRC/ADMIN_SSE_T_DEFINED
typedef struct _web/src/admin_sse_t web/src/admin_sse_t;
#define WEB/SRC/ADMIN_SSE_T_DEFINED
#endif
#ifndef WEB/SRC/ALERT_ACK_T_DEFINED
typedef struct _web/src/alert_ack_t web/src/alert_ack_t;
#define WEB/SRC/ALERT_ACK_T_DEFINED
#endif
#ifndef WEB/SRC/ALERT_LIST_T_DEFINED
typedef struct _web/src/alert_list_t web/src/alert_list_t;
#define WEB/SRC/ALERT_LIST_T_DEFINED
#endif
#ifndef WEB/SRC/ALERT_RULES_DETAIL_T_DEFINED
typedef struct _web/src/alert_rules_detail_t web/src/alert_rules_detail_t;
#define WEB/SRC/ALERT_RULES_DETAIL_T_DEFINED
#endif
#ifndef WEB/SRC/ALERT_RULES_T_DEFINED
typedef struct _web/src/alert_rules_t web/src/alert_rules_t;
#define WEB/SRC/ALERT_RULES_T_DEFINED
#endif
#ifndef WEB/SRC/ALERT_RULES_LIST_T_DEFINED
typedef struct _web/src/alert_rules_list_t web/src/alert_rules_list_t;
#define WEB/SRC/ALERT_RULES_LIST_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_DELETE_T_DEFINED
typedef struct _web/src/asset_delete_t web/src/asset_delete_t;
#define WEB/SRC/ASSET_DELETE_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_EXPORT_T_DEFINED
typedef struct _web/src/asset_export_t web/src/asset_export_t;
#define WEB/SRC/ASSET_EXPORT_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_GET_T_DEFINED
typedef struct _web/src/asset_get_t web/src/asset_get_t;
#define WEB/SRC/ASSET_GET_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_IMPORT_T_DEFINED
typedef struct _web/src/asset_import_t web/src/asset_import_t;
#define WEB/SRC/ASSET_IMPORT_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_LIST_T_DEFINED
typedef struct _web/src/asset_list_t web/src/asset_list_t;
#define WEB/SRC/ASSET_LIST_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_POST_T_DEFINED
typedef struct _web/src/asset_post_t web/src/asset_post_t;
#define WEB/SRC/ASSET_POST_T_DEFINED
#endif
#ifndef WEB/SRC/ASSET_PUT_T_DEFINED
typedef struct _web/src/asset_put_t web/src/asset_put_t;
#define WEB/SRC/ASSET_PUT_T_DEFINED
#endif
#ifndef WEB/SRC/ASSETS_IN_T_DEFINED
typedef struct _web/src/assets_in_t web/src/assets_in_t;
#define WEB/SRC/ASSETS_IN_T_DEFINED
#endif
#ifndef WEB/SRC/AUTH_T_DEFINED
typedef struct _web/src/auth_t web/src/auth_t;
#define WEB/SRC/AUTH_T_DEFINED
#endif
#ifndef WEB/SRC/AUTH-VERIFY_T_DEFINED
typedef struct _web/src/auth-verify_t web/src/auth-verify_t;
#define WEB/SRC/AUTH-VERIFY_T_DEFINED
#endif
#ifndef WEB/SRC/AVERAGE_T_DEFINED
typedef struct _web/src/average_t web/src/average_t;
#define WEB/SRC/AVERAGE_T_DEFINED
#endif
#ifndef WEB/SRC/CONFIG_T_DEFINED
typedef struct _web/src/config_t web/src/config_t;
#define WEB/SRC/CONFIG_T_DEFINED
#endif
#ifndef WEB/SRC/CONF_SCAN_T_DEFINED
typedef struct _web/src/conf_scan_t web/src/conf_scan_t;
#define WEB/SRC/CONF_SCAN_T_DEFINED
#endif
#ifndef WEB/SRC/CURRENT_T_DEFINED
typedef struct _web/src/current_t web/src/current_t;
#define WEB/SRC/CURRENT_T_DEFINED
#endif
#ifndef WEB/SRC/DATACENTER_INDICATORS_T_DEFINED
typedef struct _web/src/datacenter_indicators_t web/src/datacenter_indicators_t;
#define WEB/SRC/DATACENTER_INDICATORS_T_DEFINED
#endif
#ifndef WEB/SRC/EMAIL_FEEDBACK_T_DEFINED
typedef struct _web/src/email_feedback_t web/src/email_feedback_t;
#define WEB/SRC/EMAIL_FEEDBACK_T_DEFINED
#endif
#ifndef WEB/SRC/EMAIL_TEST_T_DEFINED
typedef struct _web/src/email_test_t web/src/email_test_t;
#define WEB/SRC/EMAIL_TEST_T_DEFINED
#endif
#ifndef WEB/SRC/EMAIL_VOTE_T_DEFINED
typedef struct _web/src/email_vote_t web/src/email_vote_t;
#define WEB/SRC/EMAIL_VOTE_T_DEFINED
#endif
#ifndef WEB/SRC/GETLOG_GET_T_DEFINED
typedef struct _web/src/getlog_get_t web/src/getlog_get_t;
#define WEB/SRC/GETLOG_GET_T_DEFINED
#endif
#ifndef WEB/SRC/GPO_ACTION_T_DEFINED
typedef struct _web/src/gpo_action_t web/src/gpo_action_t;
#define WEB/SRC/GPO_ACTION_T_DEFINED
#endif
#ifndef WEB/SRC/INFO_T_DEFINED
typedef struct _web/src/info_t web/src/info_t;
#define WEB/SRC/INFO_T_DEFINED
#endif
#ifndef WEB/SRC/INPUT_POWER_CHAIN_T_DEFINED
typedef struct _web/src/input_power_chain_t web/src/input_power_chain_t;
#define WEB/SRC/INPUT_POWER_CHAIN_T_DEFINED
#endif
#ifndef WEB/SRC/JSON_T_DEFINED
typedef struct _web/src/json_t web/src/json_t;
#define WEB/SRC/JSON_T_DEFINED
#endif
#ifndef WEB/SRC/LICENSE_T_DEFINED
typedef struct _web/src/license_t web/src/license_t;
#define WEB/SRC/LICENSE_T_DEFINED
#endif
#ifndef WEB/SRC/LICENSE_POST_T_DEFINED
typedef struct _web/src/license_post_t web/src/license_post_t;
#define WEB/SRC/LICENSE_POST_T_DEFINED
#endif
#ifndef WEB/SRC/LICENSE_STATUS_T_DEFINED
typedef struct _web/src/license_status_t web/src/license_status_t;
#define WEB/SRC/LICENSE_STATUS_T_DEFINED
#endif
#ifndef WEB/SRC/LICENSE_TEXT_T_DEFINED
typedef struct _web/src/license_text_t web/src/license_text_t;
#define WEB/SRC/LICENSE_TEXT_T_DEFINED
#endif
#ifndef WEB/SRC/LIST_GPIO_T_DEFINED
typedef struct _web/src/list_gpio_t web/src/list_gpio_t;
#define WEB/SRC/LIST_GPIO_T_DEFINED
#endif
#ifndef WEB/SRC/MY_PROFILE_T_DEFINED
typedef struct _web/src/my_profile_t web/src/my_profile_t;
#define WEB/SRC/MY_PROFILE_T_DEFINED
#endif
#ifndef WEB/SRC/NETCFG_T_DEFINED
typedef struct _web/src/netcfg_t web/src/netcfg_t;
#define WEB/SRC/NETCFG_T_DEFINED
#endif
#ifndef WEB/SRC/NOT_FOUND_T_DEFINED
typedef struct _web/src/not_found_t web/src/not_found_t;
#define WEB/SRC/NOT_FOUND_T_DEFINED
#endif
#ifndef WEB/SRC/RACK_TOTAL_T_DEFINED
typedef struct _web/src/rack_total_t web/src/rack_total_t;
#define WEB/SRC/RACK_TOTAL_T_DEFINED
#endif
#ifndef WEB/SRC/SCAN_PROGRESS_T_DEFINED
typedef struct _web/src/scan_progress_t web/src/scan_progress_t;
#define WEB/SRC/SCAN_PROGRESS_T_DEFINED
#endif
#ifndef WEB/SRC/SCAN_RUN_T_DEFINED
typedef struct _web/src/scan_run_t web/src/scan_run_t;
#define WEB/SRC/SCAN_RUN_T_DEFINED
#endif
#ifndef WEB/SRC/SECURITY_HEADERS_T_DEFINED
typedef struct _web/src/security_headers_t web/src/security_headers_t;
#define WEB/SRC/SECURITY_HEADERS_T_DEFINED
#endif
#ifndef WEB/SRC/SERVER_STATUS_T_DEFINED
typedef struct _web/src/server_status_t web/src/server_status_t;
#define WEB/SRC/SERVER_STATUS_T_DEFINED
#endif
#ifndef WEB/SRC/SSL-REDIRECT_T_DEFINED
typedef struct _web/src/ssl-redirect_t web/src/ssl-redirect_t;
#define WEB/SRC/SSL-REDIRECT_T_DEFINED
#endif
#ifndef WEB/SRC/SYSINFO_T_DEFINED
typedef struct _web/src/sysinfo_t web/src/sysinfo_t;
#define WEB/SRC/SYSINFO_T_DEFINED
#endif
#ifndef WEB/SRC/SYSTEMCTL_T_DEFINED
typedef struct _web/src/systemctl_t web/src/systemctl_t;
#define WEB/SRC/SYSTEMCTL_T_DEFINED
#endif
#ifndef WEB/SRC/TIME_T_DEFINED
typedef struct _web/src/time_t web/src/time_t;
#define WEB/SRC/TIME_T_DEFINED
#endif
#ifndef WEB/SRC/UPTIME_T_DEFINED
typedef struct _web/src/uptime_t web/src/uptime_t;
#define WEB/SRC/UPTIME_T_DEFINED
#endif
#ifndef WEB/SRC/TOPOLOGY_LOCATION_FROM2_T_DEFINED
typedef struct _web/src/topology_location_from2_t web/src/topology_location_from2_t;
#define WEB/SRC/TOPOLOGY_LOCATION_FROM2_T_DEFINED
#endif
#ifndef WEB/SRC/TOPOLOGY_LOCATION_FROM_T_DEFINED
typedef struct _web/src/topology_location_from_t web/src/topology_location_from_t;
#define WEB/SRC/TOPOLOGY_LOCATION_FROM_T_DEFINED
#endif
#ifndef WEB/SRC/TOPOLOGY_LOCATION_TO_T_DEFINED
typedef struct _web/src/topology_location_to_t web/src/topology_location_to_t;
#define WEB/SRC/TOPOLOGY_LOCATION_TO_T_DEFINED
#endif
#ifndef WEB/SRC/TOPOLOGY_POWER_T_DEFINED
typedef struct _web/src/topology_power_t web/src/topology_power_t;
#define WEB/SRC/TOPOLOGY_POWER_T_DEFINED
#endif
#ifndef WEB/SRC/ADMIN_PASSWD_T_DEFINED
typedef struct _web/src/admin_passwd_t web/src/admin_passwd_t;
#define WEB/SRC/ADMIN_PASSWD_T_DEFINED
#endif

//  Internal API

#include "db/agentstate/agentstate.h"
#include "db/asset_general.h"
#include "db/assets/assetcr.h"
#include "db/assets/assetd.h"
#include "db/assets/assetr.h"
#include "db/assets/assetu.h"
#include "db/inout/exportcsv.h"
#include "db/inout/importcsv.h"
#include "msg/asset_msg.h"
#include "msg/common_msg.h"
#include "persist/assetcrud.h"
#include "persist/assettopology.h"
#include "persist/dbhelpers.h"
#include "persist/monitor.h"
#include "persist/persist_error.h"
#include "shared/magic.h"
#include "warranty/warranty-metric.h"
#include "web/src/add_gpio.h"
#include "web/src/admin_iface.h"
#include "web/src/admin_ifaces.h"
#include "web/src/admin_sse.h"
#include "web/src/alert_ack.h"
#include "web/src/alert_list.h"
#include "web/src/alert_rules_detail.h"
#include "web/src/alert_rules.h"
#include "web/src/alert_rules_list.h"
#include "web/src/asset_DELETE.h"
#include "web/src/asset_export.h"
#include "web/src/asset_GET.h"
#include "web/src/asset_import.h"
#include "web/src/asset_list.h"
#include "web/src/asset_POST.h"
#include "web/src/asset_PUT.h"
#include "web/src/assets_in.h"
#include "web/src/auth.h"
#include "web/src/auth-verify.h"
#include "web/src/average.h"
#include "web/src/config.h"
#include "web/src/conf_scan.h"
#include "web/src/current.h"
#include "web/src/datacenter_indicators.h"
#include "web/src/email_feedback.h"
#include "web/src/email_test.h"
#include "web/src/email_vote.h"
#include "web/src/getlog_GET.h"
#include "web/src/gpo_action.h"
#include "web/src/info.h"
#include "web/src/input_power_chain.h"
#include "web/src/json.h"
#include "web/src/license.h"
#include "web/src/license_POST.h"
#include "web/src/license_status.h"
#include "web/src/license_text.h"
#include "web/src/list_gpio.h"
#include "web/src/my_profile.h"
#include "web/src/netcfg.h"
#include "web/src/not_found.h"
#include "web/src/rack_total.h"
#include "web/src/scan_progress.h"
#include "web/src/scan_run.h"
#include "web/src/security_headers.h"
#include "web/src/server_status.h"
#include "web/src/ssl-redirect.h"
#include "web/src/sysinfo.h"
#include "web/src/systemctl.h"
#include "web/src/time.h"
#include "web/src/uptime.h"
#include "web/src/topology_location_from2.h"
#include "web/src/topology_location_from.h"
#include "web/src/topology_location_to.h"
#include "web/src/topology_power.h"
#include "web/src/admin_passwd.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_REST_BUILD_DRAFT_API

//  Self test for private classes
FTY_REST_PRIVATE void
    fty_rest_private_selftest (bool verbose);

#endif // FTY_REST_BUILD_DRAFT_API

#endif
