/*  =========================================================================
    fty_rest_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_REST_CLASSES_H_INCLUDED
#define FTY_REST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-rest.h"

//  Extra headers
#include "db/agentstate.h"
#include "db/assetdef.h"
#include "db/assets.h"
#include "db/dbhelpers.h"
#include "db/inout.h"
#include "db/types.h"

//  Opaque class structures to allow forward references
#ifndef DB/AGENTSTATE/AGENTSTATE_T_DEFINED
typedef struct _db/agentstate/agentstate_t db/agentstate/agentstate_t;
#define DB/AGENTSTATE/AGENTSTATE_T_DEFINED
#endif
#ifndef DB/ASSET_GENERAL_T_DEFINED
typedef struct _db/asset_general_t db/asset_general_t;
#define DB/ASSET_GENERAL_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETCR_T_DEFINED
typedef struct _db/assets/assetcr_t db/assets/assetcr_t;
#define DB/ASSETS/ASSETCR_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETD_T_DEFINED
typedef struct _db/assets/assetd_t db/assets/assetd_t;
#define DB/ASSETS/ASSETD_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETR_T_DEFINED
typedef struct _db/assets/assetr_t db/assets/assetr_t;
#define DB/ASSETS/ASSETR_T_DEFINED
#endif
#ifndef DB/ASSETS/ASSETU_T_DEFINED
typedef struct _db/assets/assetu_t db/assets/assetu_t;
#define DB/ASSETS/ASSETU_T_DEFINED
#endif
#ifndef DB/INOUT/EXPORTCSV_T_DEFINED
typedef struct _db/inout/exportcsv_t db/inout/exportcsv_t;
#define DB/INOUT/EXPORTCSV_T_DEFINED
#endif
#ifndef DB/INOUT/IMPORTCSV_T_DEFINED
typedef struct _db/inout/importcsv_t db/inout/importcsv_t;
#define DB/INOUT/IMPORTCSV_T_DEFINED
#endif
#ifndef MSG/ASSET_MSG_T_DEFINED
typedef struct _msg/asset_msg_t msg/asset_msg_t;
#define MSG/ASSET_MSG_T_DEFINED
#endif
#ifndef MSG/COMMON_MSG_T_DEFINED
typedef struct _msg/common_msg_t msg/common_msg_t;
#define MSG/COMMON_MSG_T_DEFINED
#endif
#ifndef PERSIST/ASSETCRUD_T_DEFINED
typedef struct _persist/assetcrud_t persist/assetcrud_t;
#define PERSIST/ASSETCRUD_T_DEFINED
#endif
#ifndef PERSIST/ASSETTOPOLOGY_T_DEFINED
typedef struct _persist/assettopology_t persist/assettopology_t;
#define PERSIST/ASSETTOPOLOGY_T_DEFINED
#endif
#ifndef PERSIST/DBHELPERS_T_DEFINED
typedef struct _persist/dbhelpers_t persist/dbhelpers_t;
#define PERSIST/DBHELPERS_T_DEFINED
#endif
#ifndef PERSIST/MONITOR_T_DEFINED
typedef struct _persist/monitor_t persist/monitor_t;
#define PERSIST/MONITOR_T_DEFINED
#endif
#ifndef PERSIST/PERSIST_ERROR_T_DEFINED
typedef struct _persist/persist_error_t persist/persist_error_t;
#define PERSIST/PERSIST_ERROR_T_DEFINED
#endif
#ifndef SHARED/MAGIC_T_DEFINED
typedef struct _shared/magic_t shared/magic_t;
#define SHARED/MAGIC_T_DEFINED
#endif
#ifndef WARRANTY/WARRANTY-METRIC_T_DEFINED
typedef struct _warranty/warranty-metric_t warranty/warranty-metric_t;
#define WARRANTY/WARRANTY-METRIC_T_DEFINED
#endif
#ifndef ADD_GPIO_T_DEFINED
typedef struct _add_gpio_t add_gpio_t;
#define ADD_GPIO_T_DEFINED
#endif
#ifndef ADMIN_IFACE_T_DEFINED
typedef struct _admin_iface_t admin_iface_t;
#define ADMIN_IFACE_T_DEFINED
#endif
#ifndef ADMIN_IFACES_T_DEFINED
typedef struct _admin_ifaces_t admin_ifaces_t;
#define ADMIN_IFACES_T_DEFINED
#endif
#ifndef ADMIN_SSE_T_DEFINED
typedef struct _admin_sse_t admin_sse_t;
#define ADMIN_SSE_T_DEFINED
#endif
#ifndef ALERT_ACK_T_DEFINED
typedef struct _alert_ack_t alert_ack_t;
#define ALERT_ACK_T_DEFINED
#endif
#ifndef ALERT_LIST_T_DEFINED
typedef struct _alert_list_t alert_list_t;
#define ALERT_LIST_T_DEFINED
#endif
#ifndef ALERT_RULES_DETAIL_T_DEFINED
typedef struct _alert_rules_detail_t alert_rules_detail_t;
#define ALERT_RULES_DETAIL_T_DEFINED
#endif
#ifndef ALERT_RULES_T_DEFINED
typedef struct _alert_rules_t alert_rules_t;
#define ALERT_RULES_T_DEFINED
#endif
#ifndef ALERT_RULES_LIST_T_DEFINED
typedef struct _alert_rules_list_t alert_rules_list_t;
#define ALERT_RULES_LIST_T_DEFINED
#endif
#ifndef ASSET_DELETE_T_DEFINED
typedef struct _asset_delete_t asset_delete_t;
#define ASSET_DELETE_T_DEFINED
#endif
#ifndef ASSET_EXPORT_T_DEFINED
typedef struct _asset_export_t asset_export_t;
#define ASSET_EXPORT_T_DEFINED
#endif
#ifndef ASSET_GET_T_DEFINED
typedef struct _asset_get_t asset_get_t;
#define ASSET_GET_T_DEFINED
#endif
#ifndef ASSET_IMPORT_T_DEFINED
typedef struct _asset_import_t asset_import_t;
#define ASSET_IMPORT_T_DEFINED
#endif
#ifndef ASSET_LIST_T_DEFINED
typedef struct _asset_list_t asset_list_t;
#define ASSET_LIST_T_DEFINED
#endif
#ifndef ASSET_POST_T_DEFINED
typedef struct _asset_post_t asset_post_t;
#define ASSET_POST_T_DEFINED
#endif
#ifndef ASSET_PUT_T_DEFINED
typedef struct _asset_put_t asset_put_t;
#define ASSET_PUT_T_DEFINED
#endif
#ifndef ASSETS_IN_T_DEFINED
typedef struct _assets_in_t assets_in_t;
#define ASSETS_IN_T_DEFINED
#endif
#ifndef AUTH_T_DEFINED
typedef struct _auth_t auth_t;
#define AUTH_T_DEFINED
#endif
#ifndef AUTH-VERIFY_T_DEFINED
typedef struct _auth-verify_t auth-verify_t;
#define AUTH-VERIFY_T_DEFINED
#endif
#ifndef AVERAGE_T_DEFINED
typedef struct _average_t average_t;
#define AVERAGE_T_DEFINED
#endif
#ifndef CONFIG_T_DEFINED
typedef struct _config_t config_t;
#define CONFIG_T_DEFINED
#endif
#ifndef CONF_SCAN_T_DEFINED
typedef struct _conf_scan_t conf_scan_t;
#define CONF_SCAN_T_DEFINED
#endif
#ifndef CURRENT_T_DEFINED
typedef struct _current_t current_t;
#define CURRENT_T_DEFINED
#endif
#ifndef DATACENTER_INDICATORS_T_DEFINED
typedef struct _datacenter_indicators_t datacenter_indicators_t;
#define DATACENTER_INDICATORS_T_DEFINED
#endif
#ifndef EMAIL_FEEDBACK_T_DEFINED
typedef struct _email_feedback_t email_feedback_t;
#define EMAIL_FEEDBACK_T_DEFINED
#endif
#ifndef EMAIL_TEST_T_DEFINED
typedef struct _email_test_t email_test_t;
#define EMAIL_TEST_T_DEFINED
#endif
#ifndef EMAIL_VOTE_T_DEFINED
typedef struct _email_vote_t email_vote_t;
#define EMAIL_VOTE_T_DEFINED
#endif
#ifndef GETLOG_GET_T_DEFINED
typedef struct _getlog_get_t getlog_get_t;
#define GETLOG_GET_T_DEFINED
#endif
#ifndef GPO_ACTION_T_DEFINED
typedef struct _gpo_action_t gpo_action_t;
#define GPO_ACTION_T_DEFINED
#endif
#ifndef INFO_T_DEFINED
typedef struct _info_t info_t;
#define INFO_T_DEFINED
#endif
#ifndef INPUT_POWER_CHAIN_T_DEFINED
typedef struct _input_power_chain_t input_power_chain_t;
#define INPUT_POWER_CHAIN_T_DEFINED
#endif
#ifndef JSON_T_DEFINED
typedef struct _json_t json_t;
#define JSON_T_DEFINED
#endif
#ifndef LICENSE_T_DEFINED
typedef struct _license_t license_t;
#define LICENSE_T_DEFINED
#endif
#ifndef LICENSE_POST_T_DEFINED
typedef struct _license_post_t license_post_t;
#define LICENSE_POST_T_DEFINED
#endif
#ifndef LICENSE_STATUS_T_DEFINED
typedef struct _license_status_t license_status_t;
#define LICENSE_STATUS_T_DEFINED
#endif
#ifndef LICENSE_TEXT_T_DEFINED
typedef struct _license_text_t license_text_t;
#define LICENSE_TEXT_T_DEFINED
#endif
#ifndef LIST_GPIO_T_DEFINED
typedef struct _list_gpio_t list_gpio_t;
#define LIST_GPIO_T_DEFINED
#endif
#ifndef MY_PROFILE_T_DEFINED
typedef struct _my_profile_t my_profile_t;
#define MY_PROFILE_T_DEFINED
#endif
#ifndef NETCFG_T_DEFINED
typedef struct _netcfg_t netcfg_t;
#define NETCFG_T_DEFINED
#endif
#ifndef NOT_FOUND_T_DEFINED
typedef struct _not_found_t not_found_t;
#define NOT_FOUND_T_DEFINED
#endif
#ifndef RACK_TOTAL_T_DEFINED
typedef struct _rack_total_t rack_total_t;
#define RACK_TOTAL_T_DEFINED
#endif
#ifndef SCAN_PROGRESS_T_DEFINED
typedef struct _scan_progress_t scan_progress_t;
#define SCAN_PROGRESS_T_DEFINED
#endif
#ifndef SCAN_RUN_T_DEFINED
typedef struct _scan_run_t scan_run_t;
#define SCAN_RUN_T_DEFINED
#endif
#ifndef SECURITY_HEADERS_T_DEFINED
typedef struct _security_headers_t security_headers_t;
#define SECURITY_HEADERS_T_DEFINED
#endif
#ifndef SERVER_STATUS_T_DEFINED
typedef struct _server_status_t server_status_t;
#define SERVER_STATUS_T_DEFINED
#endif
#ifndef SSL-REDIRECT_T_DEFINED
typedef struct _ssl-redirect_t ssl-redirect_t;
#define SSL-REDIRECT_T_DEFINED
#endif
#ifndef SYSINFO_T_DEFINED
typedef struct _sysinfo_t sysinfo_t;
#define SYSINFO_T_DEFINED
#endif
#ifndef SYSTEMCTL_T_DEFINED
typedef struct _systemctl_t systemctl_t;
#define SYSTEMCTL_T_DEFINED
#endif
#ifndef TIME_T_DEFINED
typedef struct _time_t time_t;
#define TIME_T_DEFINED
#endif
#ifndef UPTIME_T_DEFINED
typedef struct _uptime_t uptime_t;
#define UPTIME_T_DEFINED
#endif
#ifndef TOPOLOGY_LOCATION_FROM2_T_DEFINED
typedef struct _topology_location_from2_t topology_location_from2_t;
#define TOPOLOGY_LOCATION_FROM2_T_DEFINED
#endif
#ifndef TOPOLOGY_LOCATION_FROM_T_DEFINED
typedef struct _topology_location_from_t topology_location_from_t;
#define TOPOLOGY_LOCATION_FROM_T_DEFINED
#endif
#ifndef TOPOLOGY_LOCATION_TO_T_DEFINED
typedef struct _topology_location_to_t topology_location_to_t;
#define TOPOLOGY_LOCATION_TO_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_T_DEFINED
typedef struct _topology_power_t topology_power_t;
#define TOPOLOGY_POWER_T_DEFINED
#endif
#ifndef ADMIN_PASSWD_T_DEFINED
typedef struct _admin_passwd_t admin_passwd_t;
#define ADMIN_PASSWD_T_DEFINED
#endif

//  Internal API

#include "db/agentstate/agentstate.h"
#include "db/asset_general.h"
#include "db/assets/assetcr.h"
#include "db/assets/assetd.h"
#include "db/assets/assetr.h"
#include "db/assets/assetu.h"
#include "db/inout/exportcsv.h"
#include "db/inout/importcsv.h"
#include "msg/asset_msg.h"
#include "msg/common_msg.h"
#include "persist/assetcrud.h"
#include "persist/assettopology.h"
#include "persist/dbhelpers.h"
#include "persist/monitor.h"
#include "persist/persist_error.h"
#include "shared/magic.h"
#include "warranty/warranty-metric.h"
#include "add_gpio.h"
#include "admin_iface.h"
#include "admin_ifaces.h"
#include "admin_sse.h"
#include "alert_ack.h"
#include "alert_list.h"
#include "alert_rules_detail.h"
#include "alert_rules.h"
#include "alert_rules_list.h"
#include "asset_DELETE.h"
#include "asset_export.h"
#include "asset_GET.h"
#include "asset_import.h"
#include "asset_list.h"
#include "asset_POST.h"
#include "asset_PUT.h"
#include "assets_in.h"
#include "auth.h"
#include "auth-verify.h"
#include "average.h"
#include "config.h"
#include "conf_scan.h"
#include "current.h"
#include "datacenter_indicators.h"
#include "email_feedback.h"
#include "email_test.h"
#include "email_vote.h"
#include "getlog_GET.h"
#include "gpo_action.h"
#include "info.h"
#include "input_power_chain.h"
#include "json.h"
#include "license.h"
#include "license_POST.h"
#include "license_status.h"
#include "license_text.h"
#include "list_gpio.h"
#include "my_profile.h"
#include "netcfg.h"
#include "not_found.h"
#include "rack_total.h"
#include "scan_progress.h"
#include "scan_run.h"
#include "security_headers.h"
#include "server_status.h"
#include "ssl-redirect.h"
#include "sysinfo.h"
#include "systemctl.h"
#include "time.h"
#include "uptime.h"
#include "topology_location_from2.h"
#include "topology_location_from.h"
#include "topology_location_to.h"
#include "topology_power.h"
#include "admin_passwd.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_REST_BUILD_DRAFT_API

//  Self test for private classes
FTY_REST_PRIVATE void
    fty_rest_private_selftest (bool verbose);

#endif // FTY_REST_BUILD_DRAFT_API

#endif
